ALTER SESSION SET "_oracle_script"=TRUE;

CREATE TABLESPACE TS_PDB
DATAFILE 'TS_PDB.DBF' 
SIZE 10M;

CREATE TEMPORARY TABLESPACE TS_PDB_TEMP
TEMPFILE 'TS_PDB_TEMP.DBF' 
SIZE 10M;

CREATE ROLE RL_PDB;
GRANT CREATE SESSION TO RL_PDB;
GRANT CREATE TABLE TO RL_PDB;
GRANT ALTER ANY TABLE TO RL_PDB;

CREATE PROFILE PF_PDB LIMIT FAILED_LOGIN_ATTEMPTS 5 PASSWORD_LIFE_TIME 100;

CREATE USER U1_SHM_PDB 
IDENTIFIED BY password
DEFAULT TABLESPACE TS_PDB
TEMPORARY TABLESPACE TS_PDB_TEMP
PROFILE PF_PDB
ACCOUNT UNLOCK;

GRANT RL_PDB TO U1_SHM_PDB;

ALTER USER U1_SHM_PDB QUOTA 2M ON TS_PDB;
select * from all_users;


SELECT TABLESPACE_NAME FROM SYS.DBA_TABLESPACES;
SELECT FILE_NAME FROM SYS.DBA_TEMP_FILES;
SELECT FILE_NAME FROM SYS.DBA_DATA_FILES;
SELECT ROLE FROM SYS.DBA_ROLES;
SELECT GRANTEE, PRIVILEGE FROM SYS.DBA_SYS_PRIVS;
SELECT PROFILE FROM SYS.DBA_PROFILES;
SELECT USERNAME FROM SYS.DBA_USERS;