Create table SHM_TABLE(
ID NUMBER,
NAME VARCHAR2(10)
);

INSERT INTO SHM_TABLE(ID, NAME) VALUES (1, 'Yana');
INSERT INTO SHM_TABLE(ID, NAME) VALUES (2, 'Vika');
INSERT INTO SHM_TABLE(ID, NAME) VALUES (3, 'Karianna');

drop  table SHM_TABLE

SELECT * FROM SHM_TABLE;